#!/usr/bin/env bash

cd server

CWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )


# start ningx using local config file
sudo nginx -c $CWD/nginx.conf

# start upload server
nohup coffee upload-server.coffee &> upload-server.log &

# start processing server
source activate maskiton
source ../deps/deps.bashrc
nohup python process-server.py &> process-server.log &

