#!/usr/bin/env bash

CWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd ${CWD}

# start upload server
nohup coffee upload-server.coffee &> upload-server.log &

# start processing server
source /nis/sw/init.bashrc
nis-enable eman
nis-enable xmipp2
nohup python process-server.py &> process-server.log &

