#!/usr/bin/env bash

CWD=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

cd ${CWD}

# start upload server
nohup coffee upload-server.coffee &> upload-server.log &

# start processing server
nohup python process-server.py &> process-server.log &

